name : Hello Github Actions

on:
  push:
   branches: [develop]
    
jobs:
  say_Hello:
    runs-on: ubuntu-latest
    steps: 
     -  name: Print Greeting
        run: echo "Hello, from Github Actions!"